# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dottor Paolo Pasquini
email: paolocarlopasquini@gmail.com
description: Profilo professionale del Dottor Paolo Carlo Pasquini, specialista in Urologia Andrologo e Dirigente Medico SC Urologia EO Galliera Genova
baseurl: "paolopasquini.gitlab.io/paolopasquini"

# Build settings
markdown: kramdown
exclude: ["README.md"]
